// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uxHzL96BRXzPFjeY5MU6oudisIqgSQ4',
    appId: '1:600444566354:web:6e56444b0c30c09ec0588b',
    messagingSenderId: '600444566354',
    projectId: 'finalexam-1b0d9',
    authDomain: 'finalexam-1b0d9.firebaseapp.com',
    storageBucket: 'finalexam-1b0d9.appspot.com',
    measurementId: 'G-Z430TPCZMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3n5w4oKEMIPF6iqPifXx60Bh3GbOsvHU',
    appId: '1:600444566354:android:1cdf68ac108d6b6bc0588b',
    messagingSenderId: '600444566354',
    projectId: 'finalexam-1b0d9',
    storageBucket: 'finalexam-1b0d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0jxe5oa4dS6PsUq_zsQ_uRDplqwD2lRM',
    appId: '1:600444566354:ios:dc22e092ca3028e9c0588b',
    messagingSenderId: '600444566354',
    projectId: 'finalexam-1b0d9',
    storageBucket: 'finalexam-1b0d9.appspot.com',
    iosClientId: '600444566354-s34a43n29gkmof69vgtlntgngl2ldpk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFileSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0jxe5oa4dS6PsUq_zsQ_uRDplqwD2lRM',
    appId: '1:600444566354:ios:dc22e092ca3028e9c0588b',
    messagingSenderId: '600444566354',
    projectId: 'finalexam-1b0d9',
    storageBucket: 'finalexam-1b0d9.appspot.com',
    iosClientId: '600444566354-s34a43n29gkmof69vgtlntgngl2ldpk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFileSharingApp',
  );
}
